version: "3"

services:
  digiboxapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: Digibox.Api/Dockerfile
    volumes:
      - './storage/keys:/root/.aspnet/DataProtection-Keys'
    networks:
      - backend
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
    container_name: sqlserver2019
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: PasswordO1.
      MSSQL_PID: Express
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - backend

networks:
  backend:
    external: true
